### ISSUE TITLE
GitLab - Missing required parameter: client_id.

### ISSUE THREAD

**Issue by jamestagal** [plentico/plenti#193]
Hi @jimafisk 

I thought I just test out version v0.5.5 of Plenti and created a new project then went to the login page. Then logged in with my Gitlab account and got in successfully but got  the following error message:
![Screen Shot 2022-06-01 at 11 30 37 pm](https://user-images.githubusercontent.com/6309595/171416789-1a8b4f1e-f427-457c-b7d3-a90afaebd81b.png)

So the app stopped here. Do you know what I should have done here? How can i fix this ?

Cheers,
Ben

**Comment by jamestagal** [comment]
Hi  @jimafisk 
Below is my Gitlab url from that error.

```
https://gitlab.com/oauth/authorize?client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fadmin%2F&response_type=code&state=J5tSD5kwaStymaMxQ8EgCT218wJA6NSDaF0-ghnQxD3eQj0Y5CE84oy.ASNNY.70opsouOP5FH3DL6agOfCat0nXgko47HAcsLreHeYTfnM3o1ozDtkgUH1ZTrhsX44Z&code_challenge=aU5_3JuihqZwJVgKqnR_2o91U1VvLLhTSXz1DYybroc&code_challenge_method=S256
```
I found this GitLab [OAuth 2.0 identity provider API](https://docs.gitlab.com/ee/api/oauth2.html) page but couldn't make much sense of it. 

Ben

**Comment by jimafisk** [comment]
Thanks for testing this out @jamestagal! There's a couple of things I would check to make sure the connection is good:

1. Did you create an OAuth app for your GitLab repo: https://youtu.be/iSR1nlKn1H4?t=12
2. Did you updated your `plenti.json` file so it points to your repo and references the app_id from GitLab: https://youtu.be/iSR1nlKn1H4?t=207

Keep in mind that things are still heavily in motion, so there will definitely be some bugs. Also if you're working locally it still commits changes to the remote repo so the workflow is a little wonky for now, but we have plans to make this seamless in the future.

**Comment by jamestagal** [comment]
Thanks for your quick reply @jimafisk . ☺️  No i didn't have these in place... thanks for the pointer... i will fix them and let you know. Good night.. from me..😴

**Comment by jamestagal** [comment]
Hi @jimafisk 
I have worked through connecting my local plenti project to Gitlab and now can login via the Admin button. Thanks for that video. What i am not able to do is set the CI/CD part working...I have that modified ```.gitlab-ci.yml``` file in project but that doesn't seem to trigger the runner! so I'm not sure... I invited you to my project so if you don't mind could take a look at my set up? 
Cheers,
Ben

**Comment by jimafisk** [comment]
Nice work @jamestagal! I pushed some changes:
- moved the project files to the top level
- changed CI to use the default branch
- updated the baseurl to work with your repo name
- updated the cms settings to connect to your remotely hosted site

If you're signed into your GitLab account, you should be able to visit your site at https://myplentisite.gitlab.io/my-plenti-site/. I couldn't edit your OAuth app because I don't have permissions on your group, but just add https://myplentisite.gitlab.io/my-plenti-site/admin to the redirect URLs and you should be all set. Once you do that you should be login and make site updates!

**Comment by jamestagal** [comment]
Oh great thanks @jimafisk 

I just tried to added that url for redirect but still get an error when trying to authenticate. . ```The redirect URI included is not valid.``` I try to give you permission so you can have a look. 
It does seem to suggest you have permission.
![2022-06-03_12-43-00](https://user-images.githubusercontent.com/6309595/171776443-be9007f2-f299-431b-87de-4c50ba42fa44.png)
but I will investigate more ! and let you know.

Thanks again for making all those changes!

Ben

**Comment by jimafisk** [comment]
Sorry, I screwed up the redirect url on my end but just pushed an update. I needed to open up a new incognito window to get it working because it was caching the old value, but it seems to be working for me now:

<details>
<summary>See screenshot</summary>

![working](https://user-images.githubusercontent.com/5913244/171779535-183415b8-aa66-440c-b995-499a9a6ecc8e.png)


</details>

Any luck on your end?

**Comment by jamestagal** [comment]
Thanks @jimafisk 
Yes it looks to be working now...was about to authentic on login and it just published an update on that page!
Excellent. Thanks again.
So I think i need to pull back the repo if I want to see changes locally? but I probably don't need to really...my main purpose was to test out what you have been working on... Oh and I didn't have to use incognito mode to get it working. 

Great work Jim. I'm excited about your project and look forward to more!! I'm sure it will be a hit with many people. I'm a good test audience because I am a teacher in edtech and like learning about this technology and see the benefits, and your goal but also I am not a developer so if I can help do any testing, I'm happy to help.
Also I think Plentico is unique in this space with a "serverless cms" and being context-aware/discoverable ...so it is not just about low cost, you want to market it on the experience ..the simplified workflow, ease of use etc...eventually anyway:)

Cheers,
Ben

**Comment by jimafisk** [comment]
> So I think i need to pull back the repo if I want to see changes locally

Yeah for now it has an awkward workflow for local, but that will change. Eventually if you spin up a local site, you should be able to login to the website, even without a GitLab account, and make changes that will write to your local JSON. We just wanted to get the remote workflow working first so it would allow people to edit a site without pulling it down locally at all. Then changes you make should kick of CI to rebuild the site and automatically redeploy them to the remote url.

> I didn't have to use incognito mode to get it working

Nice, that's good to know! I'm testing out several plenti sites on my end, so I might have had some conflicts. There will definitely be things we need to iron out to make the experience more consistent and reduce errors.

> so if I can help do any testing, I'm happy to help

Hugely appreciated! Testing is going to be key, there are so many edge cases that it will be helpful if people can report errors with clear instructions about what they did to produce the error. Hopefully we'll be ready with a beta soon!

>  Plentico is unique in this space

I appreciate that, and honestly I'm surprised more folks aren't building similar frameworks. Maybe we'll start a revolution :). Thanks for all the support on this journey, it means a lot.
